Phobos/Controllers/MessageController.cs
using AutoMapper;
using Phobos.ActionFilter;
using Phobos.Library.Interfaces;
using Phobos.Library.Interfaces.Services;
using Phobos.Library.Models.Enums;
using Phobos.Library.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using Phobos.Library.Models;
using Ninject;
using Ninject.Extensions.Logging;
using Phobos.App_Utils;

namespace Phobos.Controllers
{
    [ActionAutorize]
    [PhobosInitialization]
    public class MessageController : Controller
    {
        private IUserManagementService userManagementService;
        private IMessageService messageService;
        private ILogger logger;

        public MessageController(
            IMessageService messageService,
            IUserManagementService userManagementService,
            ILogger logger)
        {
            this.userManagementService = userManagementService;
            this.messageService = messageService;
            this.logger = logger;
        }

        public ActionResult Index(int? id)
        {
            var foldersForUser = messageService.GetAllFoldersForUser(SessionManager.CurrentUsername);
            var currentFolder = messageService.GetFolder(SessionManager.CurrentUsername, id);
            var mapper = AutoMapperConfiguration.GetMapper();

            var currentFolderViewModel = mapper.Map<UserMessageFolder, MessageMailBoxFolderViewModel>(currentFolder);
            currentFolderViewModel.Folders = mapper.Map<List<UserMessageFolder>, List<MessageMailBoxFolderViewModel>>(foldersForUser);

            var model = new MessageMailBoxViewModel()
            {
                CurrentFolder = currentFolderViewModel,
                Folders = mapper.Map<List<UserMessageFolder>, List<MessageMailBoxFolderViewModel>>(foldersForUser)
            };

            SessionManager.CurrentFolderId = currentFolder.Id;

            return View(model);
        }

        public ActionResult GetFolderBox()
        {
            var mapper = AutoMapperConfiguration.GetMapper();

            var foldersForUser = messageService.GetAllFoldersForUser(SessionManager.CurrentUsername);
            var viewModel = mapper.Map<List<UserMessageFolder>, List<MessageMailBoxFolderViewModel>>(foldersForUser);
            return this.PartialView("_FolderBox", viewModel);
        }

        public ActionResult Compose()
        {
            UserMessage model = new UserMessage() { };
            model.Owner = model.Sender = userManagementService.GetUser(SessionManager.CurrentUsername);
            MessageMailBoxItemViewModel newMessage = AutoMapperConfiguration.GetMapper().Map<MessageMailBoxItemViewModel>(model);
            return View(newMessage);
        }

        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateInput(false)]
        public ActionResult Compose(string submit, MessageMailBoxItemViewModel model, IEnumerable<HttpPostedFileBase> files)
        {
            if (submit == "Send")
            {
                UserMessage newMessage = AutoMapperConfiguration.GetMapper().Map<UserMessage>(model);

                //// newMessage.Attachments = this.SaveAttachements(files);

                newMessage = messageService.SendMessage(SessionManager.CurrentUsername, newMessage);

                return this.RedirectToAction("ReadMessage", new { id = newMessage.Id });
            }
            else if (submit == "Draft")
            {
                UserMessage newMessage = AutoMapperConfiguration.GetMapper().Map<UserMessage>(model);

                ////  newMessage.Attachments = this.SaveAttachements(files);

                UserMessage createdMessage = messageService.SaveMessage(SessionManager.CurrentUsername, newMessage);

                return this.RedirectToAction("Index", new { id = createdMessage.Folder.Id });
            }
            else if (submit == "Discard")
            {
                if (model.MessageId > 0)
                {
                    messageService.DeleteMessage(SessionManager.CurrentUsername, model.MessageId);
                }

                return this.RedirectToAction("Index");
            }

            return this.View(model);
        }

        public ActionResult MarkAsFavorite(int Id, string returnUrl)
        {
                var message = messageService.GetMessage(SessionManager.CurrentUsername, Id);
                message.IsFavorite = !message.IsFavorite;
                messageService.SaveMessage(SessionManager.CurrentUsername, message);

            return this.Redirect(returnUrl);
        }

        public ActionResult ReadMessage(int Id)
        {
            var message = messageService.GetMessage(SessionManager.CurrentUsername, Id);

            if (message == null)
            {
                return this.RedirectToAction("Index");
            }

            if (message.Owner.Username == SessionManager.CurrentUsername && message.IsDraft)
            {
                MessageMailBoxItemViewModel newMessage = AutoMapperConfiguration.GetMapper().Map<MessageMailBoxItemViewModel>(message);
                return View("Compose", newMessage);
            }
            else
            {
                MessageMailBoxItemViewModel newMessage = AutoMapperConfiguration.GetMapper().Map<MessageMailBoxItemViewModel>(message);

                return View(newMessage);
            }
        }

        public ActionResult FindNextMessage(int Id, bool IsPrevious = false)
        {
            UserMessage message = messageService.GetMessage(SessionManager.CurrentUsername, Id);
            var folder = messageService.GetFolder(SessionManager.CurrentUsername, message.Folder.Id);
            int currentElementIndex = folder.Messages.Select(x => x.Id).ToList().IndexOf(message.Id);
            int nextElementIndex = IsPrevious ? currentElementIndex - 1 : currentElementIndex + 1;


            if (IsPrevious && nextElementIndex < 0)
            {
                nextElementIndex = folder.Messages.Count - 1;
            }
            else if (!IsPrevious && nextElementIndex > folder.Messages.Count - 1)
            {
                nextElementIndex = 0;
            }

            return this.RedirectToAction("ReadMessage", new { Id = folder.Messages[nextElementIndex].Id });
        }

        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Remove(string[] selectedIds)
        {
            if (selectedIds != null && selectedIds.Count() > 0)
            {
                foreach (var selectedId in selectedIds)
                {
                    int selectedInt = 0;
                    if (int.TryParse(selectedId, out selectedInt))
                    {
                        this.messageService.DeleteMessage(SessionManager.CurrentUsername, selectedInt);
                    }
                }
            }
            return this.RedirectToAction("Index");
        }


        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Move(string newFolderId, string[] selectedIds)
        {
            if (selectedIds != null && selectedIds.Count() > 0)
            {
                foreach (var selectedId in selectedIds)
                {
                    int selectedInt = 0;
                    int newFolderIdInt = 0;

                    if (int.TryParse(selectedId, out selectedInt))
                    {
                        if (int.TryParse(newFolderId, out newFolderIdInt))
                        {
                            this.messageService.MoveMessageToFolder(SessionManager.CurrentUsername, selectedInt, newFolderIdInt);
                        }
                    }
                }
            }
            return this.RedirectToAction("Index");
        }

        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Search(string search)
        {
            return this.RedirectToAction("Index");
        }

        public ActionResult EditFolder(int Id)
        {
            var mapper = AutoMapperConfiguration.GetMapper();
            var foldersForUser = messageService.GetAllFoldersForUser(SessionManager.CurrentUsername);
            var folder = messageService.GetFolder(SessionManager.CurrentUsername, Id);
            if (folder != null)
            {
                var viewModel = mapper.Map<UserMessageFolder, MessageMailBoxFolderViewModel>(folder);
                viewModel.Folders = mapper.Map<List<UserMessageFolder>, List<MessageMailBoxFolderViewModel>>(foldersForUser);
                return this.View(viewModel);
            }

            return this.RedirectToAction("Index");
        }

        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EditFolder(MessageMailBoxFolderViewModel viewModel)
        {
            var mapper = AutoMapperConfiguration.GetMapper();
            var model = mapper.Map<MessageMailBoxFolderViewModel, UserMessageFolder>(viewModel);

            if (Request.Form["submit"] == "Save")
            {
                var updatedFolder = messageService.SaveFolder(SessionManager.CurrentUsername, model);
                viewModel = mapper.Map<UserMessageFolder, MessageMailBoxFolderViewModel>(updatedFolder);
            }

            var foldersForUser = messageService.GetAllFoldersForUser(SessionManager.CurrentUsername);
            var folders = mapper.Map<List<UserMessageFolder>, List<MessageMailBoxFolderViewModel>>(foldersForUser);

            return this.PartialView("_FolderBox", folders);
        }

        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult RemoveFolder(string selectedId)
        {
            messageService.DeleteFolder(SessionManager.CurrentUsername, int.Parse(selectedId));

            return this.RedirectToAction("Index");
        }

        public ActionResult CreateFolder()
        {
            var mapper = AutoMapperConfiguration.GetMapper();

Phobos/Controllers/NotificationController.cs
using Phobos.ActionFilter;
using Phobos.App_Utils;
using Phobos.Library.Interfaces.Services;
using Phobos.Library.Models;
using Phobos.Library.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phobos.Controllers
{
    [ActionAutorize]
    [PhobosInitialization]
    public class NotificationController : Controller
    {
        public INotificationService NotificationService { get; set; }

        public NotificationController(
            INotificationService notificationService)
        {
            this.NotificationService = notificationService;
        }

        public ActionResult GoToNotification(int id, string url)
        {
            this.NotificationService.MarkNotificationAsRead(id);

            if (string.IsNullOrEmpty(url))
            {
                return this.RedirectToAction("Index", "Home");
            }
            else
            {
                return this.Redirect(url);
            }
        }

        public ActionResult Index()
        {
            var notifications = NotificationService.GetNotifications(SessionManager.CurrentUsername);
            var mapper = AutoMapperConfiguration.GetMapper();

            var model = mapper.Map<List<UserNotification>, List<UserNotificationViewModel>>(notifications);

            return View(model);
        }

        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Remove(string[] selectedIds)
        {
            if (selectedIds != null && selectedIds.Count() > 0)
            {
                foreach (var selectedId in selectedIds)
                {
                    int selectedInt = 0;
                    if (int.TryParse(selectedId, out selectedInt))
                    {
                        this.NotificationService.DeleteNotification(SessionManager.CurrentUsername, selectedInt);
                    }
                }
            }
            return this.RedirectToAction("Index");
        }
    }
}

Phobos/Views/AdminLTE/Shared/_ControlSidebar.cshtml
@{
    List<SideTabViewModel> sideTabs = ViewBag.SideTabs ?? new List<SideTabViewModel>();
}
@if (sideTabs.Count > 0)
{
    <aside class="control-sidebar control-sidebar-dark">
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            @foreach (var sideTab in sideTabs)
            {
                var isActiveClass = sideTab.IsActive ? "active" : sideTab == sideTabs.First() ? "active" : "";
                <text>
                    <li class="@isActiveClass"><a href="#@sideTab.Id" data-toggle="tab"><i class="fa @sideTab.FontAwesomeIcon"></i></a></li>
                </text>
            }
        </ul>
        <div class="tab-content">
            @foreach (var sideTab in sideTabs)
            {
                var isActiveClass = sideTab.IsActive ? "active" : sideTab == sideTabs.First() ? "active" : "";
                <text>
                    <div class="tab-pane @isActiveClass" id="@sideTab.Id">
                        @{Html.RenderAction(sideTab.Action, sideTab.Controller, sideTab.RouteValues);}
                    </div>
                </text>
            }
        </div>
    </aside>
}

Phobos/Views/AdminLTE/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.PageTitle</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Styles.Render("~/Content/bootstrap")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    @Styles.Render("~/Content/AdminLTE")
    @Styles.Render("~/Content/datepicker")
    @Styles.Render("~/Content/daterangepicker")
    @Styles.Render("~/Content/MvcGrid")
    @Styles.Render("~/Content/wysihtml5")
    @Styles.Render("~/Content/select2")
    <!--[if lt IE 9]>
        @Scripts.Render("~/Content/respond")
        @Scripts.Render("~/Content/html5shiv")
    <![endif]-->
    @Scripts.Render("~/bundles/jquery")
</head>
<body class="hold-transition skin-blue sidebar-mini">
    @StackExchange.Profiling.MiniProfiler.RenderIncludes()
    <div class="wrapper">
        @Html.Partial("_MainHeader")
        @Html.Partial("_MainSidebar")
        <div class="content-wrapper">
            @RenderSection("_ContentHeader", required: false)
            <section class="content">
                @RenderBody()
                <div id="ohsnap"></div>
            </section>

        </div>
        @Html.Partial("_MainFooter")
        @Html.Partial("_ControlSidebar")
        <div class="control-sidebar-bg"></div>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/timeago")
    @Scripts.Render("~/bundles/datepicker")
    @Scripts.Render("~/bundles/input-mask")
    @Scripts.Render("~/bundles/daterangepicker")
    @Scripts.Render("~/bundles/iCheck")
    @Scripts.Render("~/bundles/MvcGrid")
    @Scripts.Render("~/bundles/wysihtml5")
    @Scripts.Render("~/bundles/typeahead")
    @Scripts.Render("~/bundles/select2")
    @Scripts.Render("~/bundles/AdminLTE")
    @RenderSection("scripts", required: false)
</body>
</html>

Phobos/Views/AdminLTE/Shared/_MainFooter.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <small> v.@ViewBag.Version</small>
        
    </div>
    <strong>Copyright &copy; @DateTime.Now.Year <a href="@ViewBag.CompanyUrl">@ViewBag.CompanyName</a>.</strong> All rights reserved.
</footer>

Phobos/Views/AdminLTE/Shared/_MainHeader.cshtml
@using Phobos.Helpers
@{
    List<SideTabViewModel> sideTabs = ViewBag.SideTabs ?? new List<SideTabViewModel>();
}
<header class="main-header">
    <a href="@Url.Content("~")" class="logo">
        <span class="logo-mini">
            @if (!string.IsNullOrEmpty((string)ViewBag.ShortPageTitle))
            {
                @Html.FirstWordInBold((string)ViewBag.ShortPageTitle)
            }
            else
            {
                <text><i class="fa fa-wrench"></i></text>
            }
        </span>
        <span class="logo-lg">@Html.FirstWordInBold((string)ViewBag.PageTitle)</span>


    </a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @Html.Partial("_MessagesMenu")
                @Html.Partial("_NotificationsMenu")
                @Html.Partial("_TasksMenu")
                @Html.Partial("_UserAccountMenu")

                @if (sideTabs.Count > 0)
                {
                    <li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                }
            </ul>
        </div>
    </nav>
</header>

Phobos/Views/AdminLTE/Shared/_MainSidebar.cshtml
@using Phobos.Helpers
@{
    UserAccountViewModel userAccount = ViewBag.UserAccount;
}
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="@userAccount.ImageUrl" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@userAccount.FullName</p>
                <a href="#"><i class="fa fa-circle @userAccount.CurrentStatus.AsTextCssClass()"></i> @userAccount.CurrentStatus</a>
            </div>
        </div>
        @Html.Partial("_Search")
        @Html.Partial("_Menu")
    </section>
</aside>

Phobos/Views/AdminLTE/Shared/_Menu.cshtml
@{
    MenuEntriesListViewModel menus = ViewBag.Menus;
}

<ul class="sidebar-menu">
    <li class="header">@menus.Title</li>
    @foreach (var item in menus)
    {
        @Html.Partial("_MenuEntry", item)
    }
</ul>

Phobos/Views/AdminLTE/Shared/_MenuEntry.cshtml
@model MenuEntriesViewModel
@{
    var classActive= Model.IsActive ? "active" : "";
}
@if (Model.Childs.Count > 0)
{
    <li class="treeview">
        <a href="#"><i class="fa fa-link"></i> <span>@Model.Text</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            @foreach (var item in Model.Childs)
            {
               <text>@Html.Partial("_MenuEntry", item)</text>
            }
        </ul>
    </li>
}
else
{
    <li class="@classActive"><a href="@Model.Url"><i class="fa fa-link"></i> <span>@Model.Text</span></a></li>
}

Phobos/Views/AdminLTE/Shared/_MessagesMenu.cshtml
@using Phobos.Helpers
@using Phobos.Library.Utils
@using Phobos.Utils;
@{
    List<UserMessageViewModel> userMessages = ViewBag.UserMessages;
}
<li class="dropdown messages-menu">

    @if (userMessages.Count > 0)
    {
        <a href="@Url.Action("Index","Message")" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">@userMessages.Count</span>
        </a>
        <ul class="dropdown-menu">
            <li class="header">You have @userMessages.Count messages</li>
            <li>
                <ul class="menu">
                    <li>
                        @foreach (var message in userMessages)
                        {
                            <a href="@Url.Action("ReadMessage","Message",new { id = message.Id})">
                                <div class="pull-left">
                                    <img src="@message.User.ImageUrl" class="img-circle" alt="@message.User.FullName">
                                </div>
                                <h4>
                                    @message.Title
                                    &nbsp;
                                    <small><i class="fa fa-clock-o"></i> <span title="@Html.TimeAgo(message.SentDate)"></span> </small>
                                </h4>
                                <p>@System.Text.RegularExpressions.Regex.Replace(message.Message, @"<[^>]*>", String.Empty)</p>
                            </a>
                        }
                    </li>
                </ul>
            </li>
            <li class="footer"><a href="@Url.Action("Index","Message")">See All Messages</a></li>
        </ul>
    }
    else
    {
        <a href="@Url.Action("Index","Message")">
            <i class="fa fa-envelope-o"></i>
            @if (userMessages.Count > 0)
            {
                <span class="label label-success">@userMessages.Count</span>
            }
        </a>
    }
</li>

Phobos/Views/AdminLTE/Shared/_NotAuthorized.cshtml
@model RegisterViewModel
@{
    Layout = null;
}

<div class="modal-content">
 
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Not Authorized - @ViewBag.Controller/@ViewBag.Action</h4>
        </div>
        <div class="modal-body form-horizontal">
            
            <div class="callout callout-danger">
                <h4>Not Authorized - @ViewBag.Controller/@ViewBag.Action</h4>

                <p>
                    You requested a non authorized area, please login with proper credentials.
                </p>
            </div>

        </div>
        <div class="modal-footer">

        </div>


</div>

Phobos/Views/AdminLTE/Shared/_NotificationsMenu.cshtml
@{
    List<UserNotificationViewModel> userNotifications = ViewBag.UserNotifications;
}



@{
    List<UserMessageViewModel> userMessages = ViewBag.UserMessages;
}
<li class="dropdown messages-menu">

    @if (userNotifications.Count > 0)
    {
        <a href="@Url.Action("Index", "Notification")">
            <i class="fa fa-bell-o"></i>
            @if (userNotifications.Count > 0)
            {
                <span class="label label-warning">@userNotifications.Count</span>
            }
        </a>
        <ul class="dropdown-menu">
            <li class="header">You have @userNotifications.Count notifications</li>
            <li>
                <ul class="menu">
                    <li>
                        @foreach (var item in userNotifications)
                        {
                            <a href="@Url.Action("GoToNotification", "Notification", new { id = item.Id })">
                                <i class="fa @item.FontAwesome @item.Color.ToCssClass()"></i> @item.Title
                            </a>
                        }
                    </li>
                </ul>
            </li>
            <li class="footer"><a href="@Url.Action("Index", "Notification")">See All</a></li>
        </ul>
    }
    else
    {
        <a href="@Url.Action("Index", "Notification")">
            <i class="fa fa-bell-o"></i>
            @if (userNotifications.Count > 0)
            {
                <span class="label label-warning">@userNotifications.Count</span>
            }
        </a>
    }
</li>

Phobos/Views/AdminLTE/Shared/_Search.cshtml
@*<form action="#" method="get" class="sidebar-form">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
            </span>
        </div>
    </form>
*@

Phobos/Views/AdminLTE/Shared/_TasksMenu.cshtml
@{
    List<UserTaskViewModel> userTasks = ViewBag.UserTasks;
}
<li class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-flag-o"></i>
        @if (userTasks.Count > 0)
        {
            <span class="label label-danger">@userTasks.Count</span>
        }
    </a>
    @if (userTasks.Count > 0)
    {
        <ul class="dropdown-menu">
            <li class="header">You have @userTasks.Count tasks</li>
            <li>
                <ul class="menu">
                    <li>
                        @foreach (var item in userTasks)
                        {
                            <a href="#">
                                <h3>
                                    @item.Title
                                    <small class="pull-right">@item.Percentage%</small>
                                </h3>
                                <div class="progress xs">
                                    <div class="progress-bar progress-bar-aqua" style="width: @item.Percentage%" role="progressbar" aria-valuenow="@item.Percentage" aria-valuemin="0" aria-valuemax="100">
                                        <span class="sr-only">@item.Percentage% Complete</span>
                                    </div>
                                </div>
                            </a>
                        }
                    </li>
                </ul>
            </li>
            <li class="footer">
                <a href="#">View all tasks</a>
            </li>
        </ul>
    }
</li>

Phobos/Views/AdminLTE/Shared/_UserAccountMenu.cshtml
@{
    UserAccountViewModel userAccount = ViewBag.UserAccount;
}
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="@userAccount.ImageUrl" class="user-image" alt="User Image">
        <span class="hidden-xs">@userAccount.FullName</span>
    </a>
    <ul class="dropdown-menu">
        <li class="user-header">
            <img src="@userAccount.ImageUrl" class="img-circle" alt="User Image">
            <p>
                @userAccount.FullName - @userAccount.Position
                <small>Member since @userAccount.MemberSince.ToString("MMM. yyyy")</small>
            </p>
        </li>
        @if (userAccount.FavoriteLinks.Count > 0)
        {
            <li class="user-body">
                @foreach (var item in userAccount.FavoriteLinks)
                {
                    <div class="col-xs-4 text-center">
                        <a href="@item.Url">@item.Text</a>
                    </div>
                }
            </li>
        }
        <li class="user-footer">
            <div class="pull-left">
                <a href="@Url.Action("EditProfile", "Account", new { username = userAccount.Username })" class="btn btn-default btn-flat">Profile</a>
            </div>
            @if (userAccount.Roles.Any(x => x.IsAdmin))
            {
                <div class="pull-left">
                    <a href="@Url.Action("ListUsers", "Account")" class="btn btn-default btn-flat">Users</a>
                </div>
            }
            <div class="pull-right">
                <a href="@Url.Action("Logout", "Account")" class="btn btn-default btn-flat">Sign out</a>
            </div>
        </li>
    </ul>
</li>